# Site settings
author: Maynard Hartman
title: Day(s) In The Life
header-img: img/home-bg.png
email: mjhartman@brighthouse.com
copyright_name: Maynard Hartman
description: > # this means to ignore newlines until "baseurl:"
  A day (sort of) by day expose of the life of a student software dev
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  maynardhartman

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
